import Script from "next/script";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  afterFooter
}: Readonly<{
  children: React.ReactNode;
  afterFooter: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {process.env.NODE_ENV === "production" && (
          <>
            <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-SPH9BX4RPD"
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-SPH9BX4RPD');
          `}
            </Script>
          </>
        )}
        <div className="bg-secondary-background flex justify-center items-center py-4 h-full">
          <div className="bg-background w-[1440px] relative rounded-4xl border-0 shadow-[0_2px_8px_color-mix(in_oklab,_var(--foreground)_20%,_transparent)] overflow-hidden">
            <Header />
            <main className="max-w-[1440px]">{children}</main>
            <Footer />
            {afterFooter}
          </div>
        </div>
      </body>
    </html>
  );
}
